common: &common
  adapter: postgresql
  username: postmateva
  password: hello15kitties
  host: localhost
  encoding: UTF8

development:
  <<: *common
  database: moonwalkers_dev
  pool: 5
  timeout: 5000

test:
  <<: *common
  database: moonwalkers_test
  pool: 5
  timeout: 5000

production:
  <<: *common
  database: moonwalkers_production
  pool: 5
  timeout: 5000
