# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DashboardEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # DashboardEntry. As you add validations to DashboardEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DashboardEntriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dashboard_entries as @dashboard_entries" do
      dashboard_entry = DashboardEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dashboard_entries).should eq([dashboard_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested dashboard_entry as @dashboard_entry" do
      dashboard_entry = DashboardEntry.create! valid_attributes
      get :show, {:id => dashboard_entry.to_param}, valid_session
      assigns(:dashboard_entry).should eq(dashboard_entry)
    end
  end

  describe "GET new" do
    it "assigns a new dashboard_entry as @dashboard_entry" do
      get :new, {}, valid_session
      assigns(:dashboard_entry).should be_a_new(DashboardEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested dashboard_entry as @dashboard_entry" do
      dashboard_entry = DashboardEntry.create! valid_attributes
      get :edit, {:id => dashboard_entry.to_param}, valid_session
      assigns(:dashboard_entry).should eq(dashboard_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DashboardEntry" do
        expect {
          post :create, {:dashboard_entry => valid_attributes}, valid_session
        }.to change(DashboardEntry, :count).by(1)
      end

      it "assigns a newly created dashboard_entry as @dashboard_entry" do
        post :create, {:dashboard_entry => valid_attributes}, valid_session
        assigns(:dashboard_entry).should be_a(DashboardEntry)
        assigns(:dashboard_entry).should be_persisted
      end

      it "redirects to the created dashboard_entry" do
        post :create, {:dashboard_entry => valid_attributes}, valid_session
        response.should redirect_to(DashboardEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dashboard_entry as @dashboard_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        DashboardEntry.any_instance.stub(:save).and_return(false)
        post :create, {:dashboard_entry => {}}, valid_session
        assigns(:dashboard_entry).should be_a_new(DashboardEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DashboardEntry.any_instance.stub(:save).and_return(false)
        post :create, {:dashboard_entry => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dashboard_entry" do
        dashboard_entry = DashboardEntry.create! valid_attributes
        # Assuming there are no other dashboard_entries in the database, this
        # specifies that the DashboardEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DashboardEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dashboard_entry.to_param, :dashboard_entry => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dashboard_entry as @dashboard_entry" do
        dashboard_entry = DashboardEntry.create! valid_attributes
        put :update, {:id => dashboard_entry.to_param, :dashboard_entry => valid_attributes}, valid_session
        assigns(:dashboard_entry).should eq(dashboard_entry)
      end

      it "redirects to the dashboard_entry" do
        dashboard_entry = DashboardEntry.create! valid_attributes
        put :update, {:id => dashboard_entry.to_param, :dashboard_entry => valid_attributes}, valid_session
        response.should redirect_to(dashboard_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the dashboard_entry as @dashboard_entry" do
        dashboard_entry = DashboardEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DashboardEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => dashboard_entry.to_param, :dashboard_entry => {}}, valid_session
        assigns(:dashboard_entry).should eq(dashboard_entry)
      end

      it "re-renders the 'edit' template" do
        dashboard_entry = DashboardEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DashboardEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => dashboard_entry.to_param, :dashboard_entry => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dashboard_entry" do
      dashboard_entry = DashboardEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => dashboard_entry.to_param}, valid_session
      }.to change(DashboardEntry, :count).by(-1)
    end

    it "redirects to the dashboard_entries list" do
      dashboard_entry = DashboardEntry.create! valid_attributes
      delete :destroy, {:id => dashboard_entry.to_param}, valid_session
      response.should redirect_to(dashboard_entries_url)
    end
  end

end
